[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/de/"
  force = true
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/en/"
  force = true
  status = 302

[[redirects]]
  from = "/de/offer"
  to = "/de/preise/"

[[redirects]]
  from = "/en/offer"
  to = "/en/prices/"

[[redirects]]
  from = "/en/about"
  to = "/en/team/"

[[redirects]]
  from = "/de/blog/gaston-datenschutz"
  to = "/de/blog/payflink-datenschutz"

[[redirects]]
  from = "/de/dokumentation/inbetriebnahme-gaston"
  to = "/de/dokumentation/inbetriebnahme-payflink"

[[redirects]]
  from = "/gaston-bestell-app.png"
  to = "/payflink-bestell-app.png"

[[redirects]]
  from = "/de/about"
  to = "/de/team/"

[[redirects]]
  from = "/de/contact"
  to = "/de/kontakt/"

[[redirects]]
  from = "/de/qr-code-demo"
  to = "/de/demo/"

[[redirects]]
  from = "/en/qr-code-demo"
  to = "/en/demo/"
